In [1]:
import pandas as pd
import os
from glob import glob
import numpy as np

In [2]:
f1=glob("report*.csv")[0]
f2=glob("OPS SuperHub learning*.xlsx")[0]
f3=glob("User list with activation*.xlsx")[0]

In [3]:
report = pd.read_csv(f1)
trainings= pd.read_excel(f2,sheet_name='All Items_MINOC_new template')
userid = pd.read_excel(f3,skiprows=4)

In [4]:
Carrotspot1= report[['Item ID','User ID','EMAIL','Attendance Status','Completion Status ID','Completion Date']]

In [5]:
Carrotspot1.rename(columns={'Attendance Status':'Item Types'}, inplace = True)
Carrotspot1['Item Types'] = Carrotspot1['Item Types'].str.replace('-COMPLETE','')

C:\Users\soan8006\Anaconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
<ipython-input-5-4fac6b29e00a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Carrotspot1['Item Types'] = Carrotspot1['Item Types'].str.replace('-COMPLETE','')

In [6]:
Carrotspot1['ItemID_Exist'] = Carrotspot1['Item ID'].isin(trainings['lms_item(1)'])

<ipython-input-6-12e0dd54c037>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Carrotspot1['ItemID_Exist'] = Carrotspot1['Item ID'].isin(trainings['lms_item(1)'])

In [7]:
Carrotspot1['EMAIL']=Carrotspot1['EMAIL'].str.upper()

<ipython-input-7-113d468af376>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Carrotspot1['EMAIL']=Carrotspot1['EMAIL'].str.upper()

In [8]:
userid['User e-mail']=userid['User e-mail'].str.upper()

In [9]:
Carrotspot1['EMAIL_Exist'] = Carrotspot1['EMAIL'].isin(userid['User e-mail'])

<ipython-input-9-2dd81f6878bd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Carrotspot1['EMAIL_Exist'] = Carrotspot1['EMAIL'].isin(userid['User e-mail'])

In [10]:
#Carrotspot1.to_excel('Test_email.xlsx')

In [11]:
def set_TF(Carrotspot1):
    if(Carrotspot1['ItemID_Exist'] and Carrotspot1['EMAIL_Exist']):
        return "True"
    else:
        return "False"

In [12]:
Carrotspot2= Carrotspot1.assign(result1=Carrotspot1.apply(set_TF, axis=1))

In [13]:
#Carrotspot2.to_excel('Test_email_final.xlsx')

In [14]:
Carrotspot2.head()

,Item ID,User ID,EMAIL,Item Types,Completion Status ID,Completion Date,ItemID_Exist,EMAIL_Exist,result1
0,010-NPPTCS100-GDA,wahu1002,HUIFANG.WANG.AP@NIELSENIQ.COM,ONL,ONL-COMPLETE,11/22/2021,False,False,False
1,010-NPPTCS100-GDA,wahu1002,HUIFANG.WANG.AP@NIELSENIQ.COM,ONL,ONL-COMPLETE,11/23/2021,False,False,False
2,010-NPPTCS100-GDA,liyi1005,YIN.LI.AP@NIELSENIQ.COM,ONL,ONL-COMPLETE,11/23/2021,False,False,False
3,010-NPPTCS100-GDA,zhka1004,KANKAN.ZHANG.AP@NIELSENIQ.COM,ONL,ONL-COMPLETE,11/23/2021,False,False,False
4,010-NPPTCS100-GDA,zhka1004,KANKAN.ZHANG.AP@NIELSENIQ.COM,ONL,ONL-COMPLETE,11/23/2021,False,False,False

In [15]:
CS2= Carrotspot2[Carrotspot2['result1']=='True']

In [16]:
CS2

,Item ID,User ID,EMAIL,Item Types,Completion Status ID,Completion Date,ItemID_Exist,EMAIL_Exist,result1
52,0273-TIME100-APMEACC,8122865,HEMANTH.B@NIELSENIQ.COM,ILT,ILT-COMPLETE,11/19/2021,True,True,True
53,0273-SSEVWC100-APMEACC,8122865,HEMANTH.B@NIELSENIQ.COM,ILT,ILT-COMPLETE,11/23/2021,True,True,True
54,0273-TIME100-APMEACC,8122932,SIDDHARTH.X.KUMAR@NIELSENIQ.COM,ILT,ILT-COMPLETE,11/19/2021,True,True,True
55,010-IP100-CMP,8122932,SIDDHARTH.X.KUMAR@NIELSENIQ.COM,ONL,ONL-COMPLETE,11/18/2021,True,True,True
56,0273-TIME100-APMEACC,8122853,PUNITH.KUMAR@NIELSENIQ.COM,ILT,ILT-COMPLETE,11/19/2021,True,True,True
...,...,...,...,...,...,...,...,...,...
2561,010-IP100-CMP,8123422,RAMIZ.CHHIPA@NIELSENIQ.COM,ONL,ONL-COMPLETE,11/19/2021,True,True,True
2562,600-PRIWPB100-GDA,8123422,RAMIZ.CHHIPA@NIELSENIQ.COM,ONL,ONL-COMPLETE,11/19/2021,True,True,True
2563,010-COC20-CMP,8123422,RAMIZ.CHHIPA@NIELSENIQ.COM,COMP,COMP-COMPLETE,11/19/2021,True,True,True
2567,010-IP100-CMP,8123550,HRISHABH.MUNOT@NIELSENIQ.COM,ONL,ONL-COMPLETE,11/22/2021,True,True,True
2568,010-COC20-CMP,8123550,HRISHABH.MUNOT@NIELSENIQ.COM,COMP,COMP-COMPLETE,11/22/2021,True,True,True

In [17]:
CS2=CS2.drop(['Item Types','Completion Status ID','Completion Date','ItemID_Exist','EMAIL_Exist'], axis=1)

In [18]:
CS2

                     Item ID  User ID                            EMAIL result1
52      0273-TIME100-APMEACC  8122865          HEMANTH.B@NIELSENIQ.COM    True
53    0273-SSEVWC100-APMEACC  8122865          HEMANTH.B@NIELSENIQ.COM    True
54      0273-TIME100-APMEACC  8122932  SIDDHARTH.X.KUMAR@NIELSENIQ.COM    True
55             010-IP100-CMP  8122932  SIDDHARTH.X.KUMAR@NIELSENIQ.COM    True
56      0273-TIME100-APMEACC  8122853       PUNITH.KUMAR@NIELSENIQ.COM    True
...                      ...      ...                              ...     ...
2561           010-IP100-CMP  8123422       RAMIZ.CHHIPA@NIELSENIQ.COM    True
2562       600-PRIWPB100-GDA  8123422       RAMIZ.CHHIPA@NIELSENIQ.COM    True
2563           010-COC20-CMP  8123422       RAMIZ.CHHIPA@NIELSENIQ.COM    True
2567           010-IP100-CMP  8123550     HRISHABH.MUNOT@NIELSENIQ.COM    True
2568           010-COC20-CMP  8123550     HRISHABH.MUNOT@NIELSENIQ.COM    True

[628 rows x 4 columns]

In [19]:
CS2.rename(columns={'EMAIL':'User e-mail'}, inplace = True)

In [20]:
mergeCS2=CS2.merge(userid,on='User e-mail')

In [21]:
mergeCS2.head()

,Item ID,User ID,User e-mail,result1,User identifier,User full name,Status,Invitation date,User activation date,User deactivation date,Manager identifier,Manager,Manager e-mail
0,0273-TIME100-APMEACC,8122865,HEMANTH.B@NIELSENIQ.COM,True,8122865,Hemanth B,Active,2021-09-21 17:47:39,2021-09-21 18:32:44,NaN,8123017,Priya Kishore Gomathi,kg.priya@nielseniq.com
1,0273-SSEVWC100-APMEACC,8122865,HEMANTH.B@NIELSENIQ.COM,True,8122865,Hemanth B,Active,2021-09-21 17:47:39,2021-09-21 18:32:44,NaN,8123017,Priya Kishore Gomathi,kg.priya@nielseniq.com
2,0273-TIME100-APMEACC,8122932,SIDDHARTH.X.KUMAR@NIELSENIQ.COM,True,8122932,Siddharth X.Kumar,Active,2021-09-21 17:47:39,2021-09-21 18:44:07,NaN,8123017,Priya Kishore Gomathi,kg.priya@nielseniq.com
3,010-IP100-CMP,8122932,SIDDHARTH.X.KUMAR@NIELSENIQ.COM,True,8122932,Siddharth X.Kumar,Active,2021-09-21 17:47:39,2021-09-21 18:44:07,NaN,8123017,Priya Kishore Gomathi,kg.priya@nielseniq.com
4,0273-TIME100-APMEACC,8122853,PUNITH.KUMAR@NIELSENIQ.COM,True,8122853,Punith Kumar,Active,2021-09-21 17:47:39,2021-09-21 17:57:16,NaN,8123017,Priya Kishore Gomathi,kg.priya@nielseniq.com

In [22]:
mergeCS2=mergeCS2.drop(['User identifier','User full name','Invitation date', 'User activation date', 'User deactivation date',
 'Manager identifier', 'Manager', 'Manager e-mail'], axis=1)

In [23]:
mergeCS2

,Item ID,User ID,User e-mail,result1,Status
0,0273-TIME100-APMEACC,8122865,HEMANTH.B@NIELSENIQ.COM,True,Active
1,0273-SSEVWC100-APMEACC,8122865,HEMANTH.B@NIELSENIQ.COM,True,Active
2,0273-TIME100-APMEACC,8122932,SIDDHARTH.X.KUMAR@NIELSENIQ.COM,True,Active
3,010-IP100-CMP,8122932,SIDDHARTH.X.KUMAR@NIELSENIQ.COM,True,Active
4,0273-TIME100-APMEACC,8122853,PUNITH.KUMAR@NIELSENIQ.COM,True,Active
...,...,...,...,...,...
623,010-IP100-CMP,8123422,RAMIZ.CHHIPA@NIELSENIQ.COM,True,Active
624,600-PRIWPB100-GDA,8123422,RAMIZ.CHHIPA@NIELSENIQ.COM,True,Active
625,010-COC20-CMP,8123422,RAMIZ.CHHIPA@NIELSENIQ.COM,True,Active
626,010-IP100-CMP,8123550,HRISHABH.MUNOT@NIELSENIQ.COM,True,Invited
627,010-COC20-CMP,8123550,HRISHABH.MUNOT@NIELSENIQ.COM,True,Invited

In [24]:
mergeCS2.to_excel('WOW_Training_Mapping.xlsx')